/* 2PC master code */
#include <pthread.h>
#include <unistd.h>
#include "tpc.h" /* generated by rpcgen */
#include "vote.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

int *results;
CLIENT **cl_arr;
char **args;

void *get_client_resp(void*);

int main(int argc, char *argv[])
{
    if (argc < 2) {
        printf("Please provide some slaves to connect to.\n");
        return 1;
    }

    // argv[1..n] are the IP addresses of the slave nodes.
    int num_slaves = argc - 1;
    args = argv;

    results = (int*)malloc(num_slaves * sizeof(int));
    cl_arr = (CLIENT**)malloc(num_slaves * sizeof(CLIENT*));

    /* Phase 1 */
    int i;
    for (i = 0; i < num_slaves; i++) {
        // XXX this should really be multi-threaded...
        results[i] = 0;
        cl_arr[i] = NULL;
        pthread_t tid = (pthread_t)i;
        pthread_create(&tid, NULL, get_client_resp, (void*)tid);
    }
    sleep(1);
    int successes = 0;
    // kill all threads
    for (i = 0; i < num_slaves; i++) {
        successes += results[i];
        pthread_cancel((pthread_t)i);
    }

    /* Phase 2 */
    if (successes == num_slaves) {
        // broadcast COMMIT to all slaves
        printf("Everyone agreed to commit! Woohoo!\n");
        return 0;
    }
    else {
        // broadcast ABORT to all slaves
        printf("Failed to find all slaves\n");
        return 1;
    }
    return 0;
}

// TODO make pthread-friendly
void *get_client_resp(void *tid)
{
    int i = (int)tid;
    cl_arr[i] = clnt_create(args[i + 1], TWO_PHASE_COMMIT_VOTE, TWO_PHASE_COMMIT_VOTE_V1, "tcp");
    if (cl_arr[i] == NULL) {
        printf("Error: could not connect to slave %s.\n", args[i + 1]);
    }
    int *result = commit_msg_1(NULL, cl_arr[i]);
    if (result == NULL || *result == VOTE_ABORT) {
        printf("Couldn't commit at slave %s.\n", args[i + 1]);
    }
    else {
        results[i] = 1;
    }
    return NULL;
}
